### DISCUSSION TITLE
how to perform multiple Boolean operations

### DISCUSSION THREAD

**Discussion by zql2021** [JuliaPhysics/SolidStateDetectors.jl#355] [Q&A] [answered]
Hello,  thanks to your previous patient answers.I have a new quesion to bother you. When I was writing the "detect_config.yaml" , for some complex structures, I want to perform multiple Boolean operations,However, it seems that solidstateDetectors does not allow me to do that. 
This is my source code, and I want to perform two Boolean operations when create the **ring** contact.
```
name: HPGeDetector
units:
  length: mm
  angle: deg
  potential: V
  temperature: K
grid:
  coordinates: cartesian
  axes:
    x:
      from: -15
      to: 15
      boundaries: inf
    y:
      from: -15
      to: 15
      boundaries: inf
    z:
      from: -5
      to: 5
      boundaries: inf
medium: vacuum
detectors:
- semiconductor:
    material: HPGe
    temperature: 78
    impurity_density:
      name: cylindrical
      r:
        init: 0
        gradient: 0
      z:
        init: 5.8*1e9
        gradient: 6.2*1e9
    charge_drift_model:
      include: ADLChargeDriftModel/drift_velocity_config.yaml
    geometry:
      union:
        - tube:
            r: 
              from: 0.0
              to: 15.0
            phi:
              from: 0.0
              to: 360
            h: 7.0   
            origin: [0,0,1.5]
        - tube:
            r: 
              from: 0.0
              to: 14.5
            phi:
              from: 0.0
              to: 360
            h: 2.5   
            origin: [0,0,-3.25]
  contacts:
  - material: HPGe
    id: 1
    potential: 450
    geometry:
      difference:
        - tube:
            r: 
              from: 0.0
              to: 15.0
            phi:
              from: 0.0
              to: 360
            h: 3.0   
            origin: [0,0,-3.5]
        - tube:
            r: 
              from: 0.0
              to: 14.5
            phi:
              from: 0.0
              to: 360
            h: 3.0   
            origin: [0,0,-3]
  - name: ring
    material: HPGe
    id: 2
    potential: 0
    geometry:
      union:
        tube: 
          r:
            from: 12
            to: 13
          phi:
            from: 0
            to: 360
          h: 0
          origin: [0,0,5]
        difference:
          - tube:
            r:
              from: 0
              to: 12
            phi:
              from: 0
              to: 360
            h: 0
            origin: [0,0,5]
          - box:
              widths: [30,22.5,0.01]
              origin: [0,0,5] 
```
I want to obtain a structure similar to the one in the image. Is there any solution or advice ? Thank you very much!
![image](https://github.com/JuliaPhysics/SolidStateDetectors.jl/assets/58914476/27b66e41-2644-455d-8461-ca418e35aaf5)
