### DISCUSSION TITLE
Questions about get_active_volume(sim.point_types) and real volume of detector

### DISCUSSION THREAD

**Discussion by zql2021** [JuliaPhysics/SolidStateDetectors.jl#374] [Q&A] [answered]
Dear Sir,
I apologize for bothering you again. I have another question regarding the total volume of my detector, which is in fact to be `pi*15*15*7 + pi*14.5*14.5*2.5 = 6599.30 mm^3. ` However, when using get_active_volume(sim.point_types), the result  is` 8.222035f0 cm^3`. **The simulation result is surprisingly larger than the actual volume, which is quite strange.( is_depleted(sim.point_types) return True,and the visualization of the detector looks perfectly normal )** 
Below is  part of my detector config. Could you please provide some suggestions on checking or debugging the code? Thank you very much.
```
name: Test
units:
  length: mm
  angle: deg
  potential: V
  temperature: K
grid:
  coordinates: cartesian
  axes:
    x:
      from: -15
      to: 15
      boundaries: inf
    y:
      from: -15
      to: 15
      boundaries: inf
    z:
      from: 0
      to: 10
      boundaries: inf
medium: vacuum
detectors:
- semiconductor:
    material: HPGe
    temperature: 78
    impurity_density:
      name: cylindrical
      r:
        init: 0
        gradient: 0
      z:
        init: -5.8e9cm^-3
        gradient: -6.2e9cm^-3
    charge_drift_model:
      include: ADLChargeDriftModel/drift_velocity_config.yaml
    geometry:
      union:
        - tube:
            r: 
              from: 0.0
              to: 15.0
            phi:
              from: 0.0
              to: 360
            h: 7.0   
            origin: [0,0,6.5]
        - tube:
            r: 
              from: 0.0
              to: 14.5
            phi:
              from: 0.0
              to: 360
            h: 2.5   
            origin: [0,0,1.75]
```

**Comment by fhagemann** [comment]
Which version of SSD are you using? 
(run `]st SolidStateDetectors`)
This config file should not work at all because the unit of the gradient is wrong (should be something `cm^-4`, not `cm^-3`) and I am surprised that no error is thrown.

I cannot check what exactly the error is because the config file is missing the contacts, so the config file cannot be parsed.

Things you could try to debug:
- Use cylindrical coordinates:
Is there any particular reason why you are simulating on a cartesian grid? Your config file looks very phi-symmetric, so you might even be able to simulate in 2D and extend to 3D if the contacts are also phi-symmetric.
By using the same symmetry for the grid as used in the primitives, you might avoid inaccuracies introduced by mapping your geometry onto a grid.
- Check the grid spacing: (e.g. `sim.point_types.grid[1].ticks` and `sim.point_types.grid[3].ticks`):
One reason why the active volume might be larger than expected could be coarse grid spacing.
The active volume sums up the volumes of all voxels that belong to depleted semiconductors.
I guess SSD creates a tick at `r = 15mm`. If the next tick is at `r = 19mm`, the voxel at `r = 15mm` extends to the midpoint which is at `17mm`. And if there is no ticks between `r = 14.5mm` and `r = 15mm`, then the voxel at `14.5mm` might extend up until `14.75mm`.
The resulting volume would then be `π*17^2 *7 + π*14.75^2*2.5 = 8064.173817453725`.
One way to avoid coarse grid spacing is by setting e.g. `max_tick_distance = 0.2mm` when calling `calculate_electric_potential!`.
- Plot the point types together with `vline!([-15,-14.5,14.5,15].*u"mm")` and `hline!([0.5,3,10].*u"mm"` to see how much the depleted voxels extend further than the expected dimension of your semiconductor
- Make the grid a bit wider than the semiconductor:
your axes range exactly the size of your detector. Try to add some mm at the top, bottom and sides.
In `get_active_volumes`, the grid is extended to outside of the world (see [here](https://github.com/JuliaPhysics/SolidStateDetectors.jl/blob/e3d9dbf5b9497bd131bad323dcd1b9c2bbd45b2e/src/ScalarPotentials/PointTypes.jl#L183-L185)) which might result in unphysical dimensions as your detector touches the boundaries of the world.

**Reply by zql2021** [reply]
The version is SolidStateDetectors v0.9.5. I have corrected the unit of the gradient ,thank you for pointing out the mistake.
 
You are right, I can simulate on cylindrical grid, I have made modifications in the latest config file and the calculation speed of the  calculate_electric_potential!() is significantly improved.
 
**The  problem seems to be caused by "The axes range exactly the size of the detector".**   After I add 1mm for the grid, the result of get_active_volume(sim.point_types)  is `6.5324206f0 cm^3`,very close to real volume `pi*15*15*7 + pi*14.5*14.5*2.5 = 6599.30 mm^3`
```
calculate_electric_potential!(sim, depletion_handling = true,
max_tick_distance = 0.2u"mm",convergence_limit=1e-6,
refinement_limits =[0.2, 0.1,0.05])
get_active_volume(sim.point_types) 
```
The grid spacing seems to be right.
sim_test.point_types.grid[1].ticks and sim_test.point_types.grid[3].ticks 
```
96-element Vector{Float32}:
 0.0
 0.00019642858
 0.00039285715
 0.00058928574
 0.0007857143
 0.0009821429
 0.0011785715
 0.001375
 0.0015714286
 0.0017678572
 ⋮
 0.015162829
 0.015223919
 0.015346101
 0.015468281
 0.015590462
 0.01566229
 0.01573412
 0.01586706
 0.016
 
 80-element Vector{Float32}:
 -0.001
 -0.00083333335
 -0.00066666666
 -0.0005
 -0.00033333333
 -0.00016666666
 -8.333333f-5
  0.0
  0.00012500002
  0.00025000004
  ⋮
  0.01
  0.010002499
  0.010005
  0.010170833
  0.010336667
  0.0105025
  0.010668334
  0.010834167
  0.011
```
However, when I plot the point types
 ```
plot(sim.point_types,full_det = true,
x=0,xlabel="y",ylabel="z",xunit=u"mm",yunit=u"mm",
size=(800,480),colorbar_titlefont=10,title="",aspect_ratio=:none, dpi=500,unitformat = :square)
vline!([-15,-14.5,14.5,15].*u"mm",legend=false)
hline!([0.5,3,10].*u"mm" ,legend=false)
```
**The voxels of the germanium crystal  close to the bottom electrode is not  depleted.**,This might be why the result of get_active_volume(sim.point_types)  6.5324206f0 cm^3 is slightly smaller than the actual value 6599.30 mm^3 .
![PointTypes_YZPlane_plus1mm_cylinder](https://github.com/JuliaPhysics/SolidStateDetectors.jl/assets/58914476/e9993242-6af6-4330-92ab-84b42d2ae1fb)

If I **change refinement_limits from [0.2, 0.1,0.05]) to  [0.2, 0.1,0.05,0.01])** in function `calculate_electric_potential!(),`  ` get_active_volume(sim.point_types)` return 6.5826445f0 cm^3,more close to  actual value.
Below is my config file, could you please have a look and offer some insights on why **The voxels of the germanium crystal  close to the bottom electrode is not  depleted (Compared to other regions, it is likely to be not depleted)?    And why  parameter refinement_limits have an obvious influence on this area**? Thanks a lot.
[Test.zip](https://github.com/JuliaPhysics/SolidStateDetectors.jl/files/14414098/Test.zip)


By the way,I set the grid's axes to :
```
grid:
  coordinates: cylindrical
  axes:
    r: 16
    phi:
      from: 0
      to: 0
      boundaries: periodic
    z:
      from: -1
      to: 11
```
based on "SolidStateDetectors.jl/examples/example_config_files/"
I am not very familiar with or clear on how to set boundary in the config file.I'd like to ask if "boundaries: periodic" is necessary in phi setting, and whether r, z need to set boundary in my detector.Thank you. Looking forward to your reply.

**Reply by fhagemann** [reply, marked as answer]
Let me try to comment on all of the points you brought up:
- I am not quite sure whether the impurity density in your config file is set correctly.
When using the `cylindrical` impurity density model, you need to pass a gradient, i.e. how much does the impurity density change per unit length. I am guessing that you want an impurity density of `-5.8e9cm^-3` at the bottom and `-6.2e9cm^-3` at the top.
In that case, the gradient would need to be `-0.4e9cm^-4`, because it increases by `-0.4e9cm^-3` over a length of `1cm` (the detector height) => `-0.4e9cm^-3 / 1cm = -0.4e9cm^-4`.
Setting the impurity density correctly is crucial to simulate correct electric fields and depletion behaviors.
- I just saw that your contacts are not phi-symmetric, so I wouldn't recommend to perform the calculation on a 2D in this case because it might lead to wrong behaviors. If you stick to cylindrical grids, this is what I would recommend for the config file:
```
grid:
  coordinates: cylindrical
  axes:
    r: 
      to: 16
      boundaries: inf
    phi:
      from: 0
      to: 0
      boundaries: periodic
    z:
      from: -1
      to: 11
      boundaries: inf
```
This is what I used to plot:
```julia
using Plots, Unitful; gr(fmt = :png)
plot(sim.detector, show_semiconductor = true, st = :samplesurface, n_samples = 100, ms = 1, ma = 0.2, 
    xlims = (-20,20).*u"mm", ylims = (-20,20).*u"mm", zlims = (-15,25).*u"mm",
    xunit = u"mm", yunit = u"mm", zunit = u"mm", size = (500,500))
```
![image](https://github.com/JuliaPhysics/SolidStateDetectors.jl/assets/30291312/7e12a7d8-8df8-47b8-93cf-8589db203d7f)

- In the plot of the point types, you are not seeing undepleted voxels. They would appear yellow (7 on the color bar).
I guess what you are referring to are the dark purple voxels at the bottom (0 on the color bar). These are voxels with fixed potentials, so usually contacts or grounded passive parts. In your case, it would be the contact you name `Anode`. <br/>
What you are seeing is that the voxels have a finite size. If you have a tick at `z = 1.0mm` (which should be in the contact) and a tick at `z = 1.2mm` (which should be in the semiconductor), then the contact voxel will reach to the midpoint, which is at `z = 1.1mm`. This effective reduces the height of the "active volume" of the lower cylinder to 2.4mm (rather than 2.5mm), which result in `π*15^2*7 + π*14.5^2 *2.4 = 6533.256082405334`.
If you set finer refinement limits, SSD adds more grid points in regions where the electric potential changes fast.
If now, another grid point gets added at `z = 1.04mm`, then the contact voxel only extends to `z = 1.02mm`, resulting in an effective height of your lower cylinder of `2.48mm` and an "active volume" of `π*15^2*7 + π*14.5^2*2.48 =6586.097670838714`. <br/>
The refinement limits have an obvious influence on the active volume, because it determines the distance between grid points and, thus, how much contacts voxels extend artificially into the semiconductor.
