### ISSUE TITLE
Wrong painting of contact surfaces when using small scales in 2D simulations

### ISSUE THREAD

**Issue by fhagemann** [JuliaPhysics/SolidStateDetectors.jl#442]
The way the painting is implemented does not seem to be optimal for small-scale structures.

#### Config file
```yaml
name: Painting
units:
  length: mm
  angle: deg
  potential: V
  temperature: K
grid:
  coordinates: cylindrical
  axes:
    r:
      to: 5
      boundaries: inf
    phi:
      from: 0
      to: 0
      boundaries: periodic
    z:
      from: -0.05
      to: 0.25
      boundaries: inf
detectors:
  - semiconductor:
      material: HPGe
      impurity_density:
        name: constant
        value: -1e9cm^-3
      geometry:
        tube:
          r: 4
          h: 0.2
          origin:
            z: 0.1
    contacts:
      - name: top
        id: 1
        potential: -2000
        material: HPGe
        geometry:
          tube:
            r: 3
            h: 0.01
            origin:
              z: 0.195
      - name: bot
        id: 2
        potential: 2000
        material: HPGe
        geometry:
          tube:
            r: 3
            h: 0.01
            origin:
              z: 0.005
```

#### Simulation code

If loading a config file with small scales and 2D simulations, the painting of `ConeMantle` gives weird results.

```julia
using SolidStateDetectors
using Plots
T = Float32
sim = Simulation{T}("painting.yaml")
apply_initial_state!(sim, ElectricPotential)
plot(sim.electric_potential, aspect_ratio = :none)
plot!(sim.detector, φ = 0, st = :slice, aspect_ratio = :none, fmt = :png, colorbar_title = "")
```
![Image](https://github.com/user-attachments/assets/f9555344-f57f-4b0f-b6b6-4fbdf285ad8c)

However, when performing a 3D simulation by changing
```yaml
    phi:
      from: 0
      to: 360
      boundaries: periodic
```
then the same plot looks fine:
![Image](https://github.com/user-attachments/assets/8fa16ad7-7719-4429-9e73-802435f6613e)
